name: Build IPA
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          find . -name "*.swift" -not -path "./.git/*"
          ls -la
